version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.8.0
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: pug
    versions:
    - 3.0.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.4.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.4.0
